name: Deploy from main
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - src/**
      - public/**
      - webpack.config.mjs
      - examples.md
      - README.md
      - TEACHERS.md
      - package.json
      - package-lock.json

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Set Git commit identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Set remote URL with token
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git

      - name: Run publish script to build and publish to gh-pages
        run: npm run publish
